version: '2.1'
services:
  gt-chatta:
    image: openjdk:8-jre
    entrypoint:
      - ./sbt
    command:
      - runMain geotrellis.chatta.Main
    ports: 
      - 8777:8777
    working_dir: /opt/geotrellis
    volumes:
      - "${HOME}/.ivy2:/root/.ivy2"
      - "${HOME}/.m2:/root/.m2"
      - "${HOME}/.sbt:/root/.sbt"
      - "./service/geotrellis/:/opt/geotrellis"
      - "./service/static:/static"
      - "./service/geotrellis/data:/data/"
  gt-chatta-ingest:
    shm_size: 10g
    build:
      context: ./service
      dockerfile: Dockerfile.ingest
    volumes:
      - "./service/geotrellis/data:/data/"